[project]
name = "dotfiles"
version = "0.1.0"
requires-python = "==3.13.5"

[dependency-groups]
dev = ["ruff==0.12.7", "pyright==1.1.403"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E731", "E501"]

[tool.pyright]
exclude = ["**/__pycache__", ".*"]
